services:
    mongo:
        image: mongo:8.0.3
        ports:
            - 27017:27017
        volumes:
            - mongo-db:/data/db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: dev

volumes:
    mongo-db:
        driver: local
