### Create a new post
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "content": "Hello World!",
    "sender": "omer@gmail.com"
}

### Retrieve all posts
GET http://localhost:3000/api/posts


### Fetch a post using its ID
GET http://localhost:3000/api/posts/6740dcf313fa52f3445c7401

### Retrieve posts from a specific sender
GET http://localhost:3000/api/posts?sender=omer@gmail.com

### Update the content of an existing post
PUT http://localhost:3000/api/posts/6740dcf313fa52f3445c7401
Content-Type: application/json

{
    "content": "Updated post content"
}

### Remove a post by its ID
DELETE http://localhost:3000/api/posts/6740e2604d09606b47c4beb6

### Add a comment to a post
POST http://localhost:3000/api/comments
Content-Type: application/json

{
  "post": "6740dcf313fa52f3445c7401",
  "content": "Amazing post!",
  "sender": "yoav@gmail.com"
}

### Get all comments across posts
GET http://localhost:3000/api/comments

### Retrieve comments for a specific post
GET http://localhost:3000/api/comments?post=6740dcf313fa52f3445c7401

### Fetch a comment using its ID
GET http://localhost:3000/api/comments/674749f912f4bd84a07fd284

### Edit a specific comment's content
PUT http://localhost:3000/api/comments/674749f912f4bd84a07fd284
Content-Type: application/json

{
  "content": "This is so inspiring!"
}

### Delete a comment by its ID
DELETE http://localhost:3000/api/comments/674749f912f4bd84a07fd284
