# Create a post
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "content": "Hey everyone!!!",
    "sender": "omer@gmail.com"
}

###

# Get all posts
GET http://localhost:3000/api/posts

###

# Get a single post by ID
GET http://localhost:3000/api/posts/167671ad1b5f4ab89bf53906445e6445

###

# Get all posts from a sender
GET http://localhost:3000/api/posts?sender=omer@gmail.com

###

# Update a post
PUT http://localhost:3000/api/posts/167671ad1b5f4ab89bf53906445e6445
Content-Type: application/json

{
    "content": "edit my post"
}

###

# Delete a post
DELETE http://localhost:3000/api/posts/167671ad1b5f4ab89bf53906445e6445

###

# Create a comment
POST http://localhost:3000/api/comments
Content-Type: application/json

{
  "post": "167671ad1b5f4ab89bf53906445e6445",
  "content": "wow, great.",
  "sender": "yoav@gmail.com"
}

###

# Get all comments
GET http://localhost:3000/api/comments

###
# Get all comments for a specific post
GET http://localhost:3000/api/comments?post=167671ad1b5f4ab89bf53906445e6445

###
# Get a comment by ID
GET http://localhost:3000/api/comments/167671ad1b5f4ab89bf53906445e6445

###
# Update a comment
PUT http://localhost:3000/api/comments/167671ad1b5f4ab89bf53906445e6445
Content-Type: application/json

{
  "content": "very cool!"
}

###
# Delete a comment
DELETE http://localhost:3000/api/comments/167671ad1b5f4ab89bf53906445e6445
